Thesis contents
EngineerDiplomaTeam/city-map-planner pull request #101
Opened 2024-04-29 20:51 UTC by WertiPL

Od czegoś trzeba zacząć 

na tą chwile jest tyle

2024-05-02 13:29 UTC, ElectroluxV2 commented
Jak dla mnie spis treści jest ok, nie wiem tylko po co podzieliłeś to na tyle plików, uważam że wcześniejszy podział (1 plik per duży rozdział) był wystarczający

2024-05-11 11:06 UTC, damiankreft approved these changes

2024-05-11 15:55 UTC, ElectroluxV2 requested changes
.

2024-05-12 10:42 UTC, ElectroluxV2 approved these changes

2024-05-12 11:05 UTC, merged