Decyzje projektowe poprawki
EngineerDiplomaTeam/city-map-planner pull request #107
Opened 2024-05-10 13:17 UTC by ElectroluxV2

2024-05-10 15:52 UTC, WertiPL commented
Wed

> Preview of thesis at latest HEAD avliable at: https://city-planner.budziszm.pl/thesis/c6bbea0dab73114478a86073446e13e3665bbfca

według wymaganego stardardu jestem za

2024-05-10 23:12 UTC, ElectroluxV2 commented
> Preview of thesis at latest HEAD avliable at: [city-planner.budziszm.pl/thesis/cad1b36331e5d56e033bf5936c3fbb8d765a17d5](https://city-planner.budziszm.pl/thesis/cad1b36331e5d56e033bf5936c3fbb8d765a17d5)

@WertiPL  @damiankreft  @s-kreft , wysłałem tą wersję mailem na PSEM

2024-05-11 11:04 UTC, damiankreft submitted a review, later dismissed
Przeczytałem zmiany. Jak dla mnie wyglądają ok. Dobra robota :)

2024-05-12 10:59 UTC, WertiPL commented
Wymagane poprawki do Oceny


wstęp akatapi ,

2 rozdział brak akapitów

Flutter(dać myśnik - przed początkiem zdania)  
NIe pogrubiać poćżatków zdania



listy punktowe z małych liter

w każdym elemencie pomiedzy przecinek albo średnik na końcu zdania

po ostatnym elemencie w liście kropka(punkcie z listy)


Za dużo enterów wystarczy wciencie w tekscie (akapit do .net/C#)


przez podwójne nawiązanie do jezyka i frameworka użyć najpierw jednego potem drugiego
nie łączyć .net i C# - (rozdzielić to)
![image](https://github.com/EngineerDiplomaTeam/city-map-planner/assets/35771128/0e951bce-4bc2-4351-b69c-d999b4d1a3f8)




Wdowy / środki (np. "W" w złym miejscu początek  zdania)
![image](https://github.com/EngineerDiplomaTeam/city-map-planner/assets/35771128/c03c9a45-fefe-4e64-8d80-914099dd7bda)

Może zaznaczyłem o jedno za dużo (wrócić do definicji wdowy)

Przegląd rynku

nazwy usług w środku akapuitu zamiast z na początku
![image](https://github.com/EngineerDiplomaTeam/city-map-planner/assets/35771128/58e103cf-ba1e-4944-be83-9bda3e252d3f)

bez enterów pomiedzy

Wystarczy wcięcie w akapicie 


BIlibiografia



najpierw nazwsko potęm pierwsza litera imienia


brakuje użycie identycznego  schematu z zajęć

2024-05-12 11:04 UTC, WertiPL requested changes
@ElectroluxV2 Wymagane poprawki do Oceny


wstęp akatapi ,

2 rozdział brak akapitów

Flutter(dać myśnik - przed początkiem zdania)  
NIe pogrubiać poćżatków zdania



listy punktowe z małych liter

w każdym elemencie pomiedzy przecinek albo średnik na końcu zdania

po ostatnym elemencie w liście kropka(punkcie z listy)


Za dużo enterów wystarczy wciencie w tekscie (akapit do .net/C#)


przez podwójne nawiązanie do jezyka i frameworka użyć najpierw jednego potem drugiego
nie łączyć .net i C# - (rozdzielić to)
![image](https://github.com/EngineerDiplomaTeam/city-map-planner/assets/35771128/0e951bce-4bc2-4351-b69c-d999b4d1a3f8)




Wdowy / środki (np. "W" w złym miejscu początek  zdania)
![image](https://github.com/EngineerDiplomaTeam/city-map-planner/assets/35771128/c03c9a45-fefe-4e64-8d80-914099dd7bda)

Może zaznaczyłem o jedno za dużo (wrócić do definicji wdowy)

Przegląd rynku

nazwy usług w środku akapuitu zamiast z na początku
![image](https://github.com/EngineerDiplomaTeam/city-map-planner/assets/35771128/58e103cf-ba1e-4944-be83-9bda3e252d3f)

bez enterów pomiedzy

Wystarczy wcięcie w akapicie 


BIlibiografia



najpierw nazwsko potęm pierwsza litera imienia


brakuje użycie identycznego  schematu z zajęć

2024-05-25 23:37 UTC, merged