Analiza Wymagania
EngineerDiplomaTeam/city-map-planner pull request #121
Opened 2024-05-28 19:39 UTC by WertiPL

2024-05-30 14:29 UTC, WertiPL commented
\section{Wymagania jakościowe i inne}
\label{sec:wymagania-jakosciowe-i-inne}

Czy dodajemy i wjakiej formie ?

bo sws tego nie obejmuje

@damiankreft @ElectroluxV2 @s-kreft

2024-05-30 14:29 UTC, WertiPL commented
Zadanie Wykonane

2024-05-31 20:35 UTC, WertiPL commented
Trzeba dodać do słownika bo nigdzie nie widziałem

Def. POI – Point of interest –tłumaczenie-> punkt w przestrzeni, najczęściej na powierzchni Ziemi, który może być użyteczny lub wart uwagi.

2024-05-31 21:09 UTC, ElectroluxV2 requested changes
Brakuje mi wymagać dla widoku kalendarza, nie rób słów z wielkiej litery w środku zdania i posprawdzaj błędy ortograficzne bo kilka mi sie rzuciło w oczy

2024-05-31 21:09 UTC, ElectroluxV2 commented on Documentation/chapters/analiza-wymagań.tex
> +\begin{requirementstab}[label={tab:requirements:env9},caption={Karta wymagania: Informacja o aktualnych danych POI }]
Powielone poprzednim, do scalenia

2024-05-31 21:09 UTC, ElectroluxV2 commented on Documentation/chapters/analiza-wymagań.tex
> +\begin{requirementstab}[label={tab:requirements:nonfunc1},caption={Karta wymagania: Dostęp 24/7}]
Dostępność rozwiązania

2024-05-31 21:09 UTC, ElectroluxV2 commented on Documentation/chapters/analiza-wymagań.tex
> +    \descr{System powinien być dostępny 7 dni w tygodniu, 24 godziny na dobę. Na potrzeby prac utrzymaniowych dopuszcza się niedostępność max 8h w skali miesiąca w godzinach nocnych (SLA 98.905 \%) }
nie używaj "max" ani innego jezyka potocznego

2024-05-31 21:09 UTC, ElectroluxV2 commented on Documentation/chapters/analiza-wymagań.tex
> +\begin{requirementstab}[label={tab:requirements:nonfunc2},caption={Karta wymagania: Responsywność Systemu na mobilnych urządzeniach}]
Systemu z małej

2024-05-31 21:09 UTC, ElectroluxV2 commented on Documentation/chapters/analiza-wymagań.tex
> +    Interaktywna mapa wraz ze znacznikami poi powinna być responsywna i działać prawidłowo na urządzeniach z ekranem dotykowym jak i urządzeniach ze wskaźnikiem analogowym (myszka)
Dopisek o mapie do wywalenia, powielony wcześniej

2024-05-31 21:35 UTC, WertiPL commented on Documentation/chapters/analiza-wymagań.tex
> +    \type{Ożywiony bezpośredni}
Typ udziałowca: | {ożywiony/nieożywiony, bezpośredni/pośredni}

Masz bezpośredni wpływ na aplikacje

2024-05-31 21:36 UTC, WertiPL commented on Documentation/chapters/analiza-wymagań.tex
> +    \descr{System powinien działać bez większych przestojów i przerw w funkcjonowaniu, nawet przy dużej liczbie użytkowników. }
tak po proszę

2024-05-31 21:48 UTC, WertiPL commented on Documentation/chapters/analiza-wymagań.tex
> +    \postconditions{ Wyświetlenie zaznaczonych atrakcji. }
Dałbym po prostu Wyświetlenie atrakcji

2024-05-31 21:57 UTC, WertiPL commented on Documentation/chapters/analiza-wymagań.tex
> +    \exceptions{ Brak grupy, której szuka użytkownik. Użytkownik musi użyć regularnego planu zajęć.   }
xd, poprawione

2024-05-31 21:58 UTC, WertiPL commented on Documentation/chapters/analiza-wymagań.tex
> +    \implementation{ Aplikacja pobiera w tle plik bazy danych ważący 1MB.  }
zaproponuj coś innego

2024-05-31 22:02 UTC, WertiPL commented
Dodanie wymagania o sychronizacji danych
dodać do słownika CRUD

2024-05-31 22:06 UTC, WertiPL commented on Documentation/chapters/analiza-wymagań.tex
> +    \implementation{ Panel administracyjny do zarządzania opiniami użytkowników (umożliwia cenzurę.).   }
Opisane w IO9

2024-05-31 22:11 UTC, WertiPL commented on Documentation/chapters/analiza-wymagań.tex
> +    \preconditions{ Mapa Atrakcji z znacznikami dodanymi przez twórców aplikacji.}
ma jakieś to znaczenie?
Admin nie może dodać nowych?

2024-06-01 09:13 UTC, ElectroluxV2 commented on Documentation/chapters/analiza-wymagań.tex
> +    \implementation{ Aplikacja pobiera w tle plik bazy danych ważący 1MB.  }
To wygląda jak przekopiowane z byt

2024-06-01 09:15 UTC, ElectroluxV2 commented on Documentation/chapters/analiza-wymagań.tex
> +    \implementation{ Aplikacja pobiera w tle plik bazy danych ważący 1MB.  }
Aplikacja wyświetla listę dostępnych atrakcji wraz z informacjami o nich, na górze listy użytkownik ma możliwość wyszukiwania atrakcji po nazwie oraz posortowania wyników po przez kliknięcie nagłówka listy. Kliknięcie wiersza otwiera widok szczegółowy atrakcji turystycznej.

2024-06-02 20:22 UTC, WertiPL commented on Documentation/chapters/analiza-wymagań.tex
> +\begin{requirementstab}[label={tab:requirements:func7},caption={Karta wymagania: Możliwość pisania opinii wraz ze zdjęciami}]
Tutaj jest trochę szersza persektywa nie tylko zdjecia
tylko tekst + zdjecia tak jak na google

poprzednie wymaganie daje możliwość tylko gwiazdek pod atrakcją

2024-06-02 20:39 UTC, WertiPL commented on Documentation/chapters/analiza-wymagań.tex
> +    \acceptcrit{Opinia musi zostać zatwierdzona przez administrator, może póżniejszym etapie na podstawie algorytmu, który spełnia jakąś polityke prywatności. }
dodane

2024-06-02 20:47 UTC, WertiPL commented on Documentation/chapters/analiza-wymagań.tex
> +    \inputdata{Wybrane atrakcje turystyczne z mapy bądź listy atrakcji,  }
nie wiem czy dobrze zrozumiałem

2024-06-02 21:22 UTC, WertiPL commented on Documentation/chapters/analiza-wymagań.tex
> +\begin{requirementstab}[label={tab:requirements:func14},caption={Karta wymagania: Zmiana Optymalnej trasy według preferencji }]
przyjrzyj się teraz F14

2024-06-08 20:11 UTC, WertiPL commented
@ElectroluxV2 
Nie zamykałem odpowiedzi, w których się wypowiedziałem, są tam pytania do dyskuji proszę się wypowiedz
Podsumowanie braków na tą chwile:
Brakuje mi wymagać dla widoku kalendarza
Dodanie wymagania o sychronizacji danych
dodać do słownika CRUD
 Zadanie nie wykonane w 100% to zależności pomiedzy wymaganiami oraz implementacja w 3 miejscach oznaczone *******

2024-06-09 05:47 UTC, ElectroluxV2 reviewed
Reszty nie jestem w stanie sprawdzić w skm

2024-06-09 05:47 UTC, ElectroluxV2 commented on Documentation/słownik-pojęć.tex
> +    description={OpenLayers to biblioteka napisana w języku JavaScript, ułatwiająca dodawanie dynamicznych map na stronach internetowych..}
Trzeba zobaczyć czy w innych pracach to jest w słowniku czy w bibliografii

2024-06-09 05:47 UTC, ElectroluxV2 commented on Documentation/słownik-pojęć.tex
> +    description={Service Level Agreement, SLA (umowa o gwarantowanym poziomie świadczenia usług) to umowa utrzymania i systematycznego poprawiania ustalonego między usługodawcą a usługobiorcą poziomu
Ucięte?

2024-06-09 05:47 UTC, ElectroluxV2 commented on Documentation/chapters/analiza-wymagań.tex
> +Wymagania dla projektu zostały wybrane przez zespół projektowy w pierwszym semestrze. Zostały określone na podstawie analizy aktualnych rozwiązań i bieżąco potrzeb użytkowników.
Aktualnie dostępnych rozwiązań i potrzeb zespołu projektowego. Nie mamy dowodów na analizę wśród użytkowników

2024-06-09 05:47 UTC, ElectroluxV2 commented on Documentation/chapters/analiza-wymagań.tex
> +        \item chce korzystać z aplikacji z listą dostępnych atrakcji w wersji pisanej
W wersji tekstowej

2024-06-11 16:19 UTC, WertiPL commented
- Dodałem powiązania, 
- sprawdziłem gramatyke, 
- ortografie,
-  przecinki,
-  poprawiona numeracja 
- usuniete duble
- Brakuje mi wymagać dla widoku kalendarza
- Sprawdzenie potrzeby wymagania o sychronizacji danych (mamy wymaganie o autoamtycznym sprawdzaniu danych)
- dodane do słownika CRUD i inne
-  implementacja w 3 miejscach oznaczone

@ElectroluxV2 
FO19
Ciebie interesowało
jest nie dokończone

2024-06-11 17:38 UTC, ElectroluxV2 approved these changes

2024-06-11 17:39 UTC, merged